spring:
  datasource:
    url: jdbc:mysql://n :3306/example
    username: root
    password: Jiangxin1035
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cc.leevi.toutiao.model
logging:
  level: info
qiniu:
  accesskey: NQxbQJg4fu9WBdShdI6WbuqCvqBuwTOweviszPWb
  secretkey: BnC3m_Jqyjx9GyGYeQ5LG3AUoExU2Q7yVhWFXyjv
  bucket: spider
  prefix: ok82k2xq6.bkt.clouddn.com
local:
  locations:
    - latitude: 1234
      longitude: 4132
    - latitude: 666
      longitude: 888