package cc.leevi.toutiao.mapper;

import cc.leevi.toutiao.model.PlanData;
import cc.leevi.toutiao.model.PlanDataExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlanDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_data
     *
     * @mbg.generated
     */
    long countByExample(PlanDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_data
     *
     * @mbg.generated
     */
    int deleteByExample(PlanDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_data
     *
     * @mbg.generated
     */
    int insert(PlanData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_data
     *
     * @mbg.generated
     */
    int insertSelective(PlanData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_data
     *
     * @mbg.generated
     */
    List<PlanData> selectByExample(PlanDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_data
     *
     * @mbg.generated
     */
    PlanData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlanData record, @Param("example") PlanDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlanData record, @Param("example") PlanDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlanData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlanData record);
}