package cc.leevi.toutiao.model;

public class PlanData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_data.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_data.plan_id
     *
     * @mbg.generated
     */
    private Integer planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_data.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_data.id
     *
     * @return the value of t_plan_data.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_data.id
     *
     * @param id the value for t_plan_data.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_data.plan_id
     *
     * @return the value of t_plan_data.plan_id
     *
     * @mbg.generated
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_data.plan_id
     *
     * @param planId the value for t_plan_data.plan_id
     *
     * @mbg.generated
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_data.content
     *
     * @return the value of t_plan_data.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_data.content
     *
     * @param content the value for t_plan_data.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}